### ISSUE TITLE
End of Herokuapp free plan

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [RemDelaporteMathurin/h-transport-materials-dashboard#73]
[Herokuapp will end their free plan in about a month.](https://blog.heroku.com/next-chapter)

We need to either move to a paid plan or find some alternative.

Any ideas?

**Comment by RemDelaporteMathurin** [comment]
@shimwell you have many dash powered apps that don't run on Herokuapp, would you mind giving your opinion?

**Comment by shimwell** [comment]
I have used and still use two different options

google cloud build, this is hooked up to the git repo and when the git repo has a merge to main then the docker image containing the app is rebuilt on gcloud and hosted.

I also use [zappa](https://github.com/zappa/Zappa) to deploy docker images to AWS. Tutorial [here](https://ianwhitestone.work/zappa-serverless-docker/)

**Comment by RemDelaporteMathurin** [comment]
google cloud build seems interesting!
does it produce a URL too?

**Comment by shimwell** [comment]
you get a url like this one https://isotope-xs-plotter-4zf6u4tg6a-lz.a.run.app/ which you can then map to a domain like this one http://isotope-plotter.xsplot.com/

**Comment by RemDelaporteMathurin** [comment]
@shimwell I tried adding a Dockerfile on [this branch](https://github.com/RemDelaporteMathurin/h-transport-materials-dashboard/tree/docker_image)

When running:

```
docker build -t htm_dashboard
docker run --network host -t htm_dashboard
```

It produces:

```
PS D:\Projets\h-transport-materials-dashboard> docker run --network host -t htm_dashboard
[2022-10-21 15:41:06 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-10-21 15:41:06 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2022-10-21 15:41:06 +0000] [1] [INFO] Using worker: gthread
[2022-10-21 15:41:06 +0000] [9] [INFO] Booting worker with pid: 9
```

But http://0.0.0.0:8080 displays nothing.

Any idea off the top of your head?

**Comment by shimwell** [comment]
hummm not sure, that all looks correct to me

**Comment by RemDelaporteMathurin** [comment]
Right, I have the same behaviour with isotope-xs-plotter

**Comment by shimwell** [comment]
how about the app.py 

https://github.com/RemDelaporteMathurin/h-transport-materials-dashboard/pull/74

**Comment by RemDelaporteMathurin** [comment]
Maybe the port 8080 is blocked on Windows. I'll try with 8050

**Comment by RemDelaporteMathurin** [comment]
Nah same thing with 8050.

**Comment by RemDelaporteMathurin** [comment]
Ok, I think it's a windows issue: it works on google cloud services: https://htm-dashboard-uan5l4xr6a-od.a.run.app/

**Comment by RemDelaporteMathurin** [comment]
Closing this as the google cloud route seems to work fine. Next step: try to have a proper URL and not the hashed one that we currently have. Any idea @shimwell?

**Comment by shimwell** [comment]
I think the url provided by google cloud is stable and stays the same.

You could have a html hosted by github pages, this would provide a nicer url

The html could redirect like this

```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="refresh" content="7; url='https://www.xsplot.com'" />
  </head>
</html>
```

**Comment by RemDelaporteMathurin** [comment]
That's a shout!!
